CREATE TABLE brand
(
    id   BIGINT      NOT NULL AUTO_INCREMENT,
    name VARCHAR(80) NULL DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;